# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    defaultParams: ?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    druid:
      master:
        url: jdbc:mysql://localdb.mysql.com:3307/ruoyi_vue
        username: w_account
        password: qvYx8OaG
      slave:
        url: jdbc:mysql://localdb.mysql.com:3308/ruoyi_vue
        username: r_account
        password: 63ucwRVV
      qrtz:
        url: jdbc:mysql://localdb.mysql.com:3307/ruoyi_qrtz
        username: w_account
        password: qvYx8OaG
      qrtzSlave:
        url: jdbc:mysql://localdb.mysql.com:3308/ruoyi_qrtz
        username: r_account
        password: 63ucwRVV
      log:
        url: jdbc:mysql://localdb.mysql.com:3307/ruoyi_log
        username: w_account
        password: qvYx8OaG
      logSlave:
        url: jdbc:mysql://localdb.mysql.com:3308/ruoyi_log
        username: r_account
        password: 63ucwRVV
      initialSize: 5
      minIdle: 10
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      maxEvictableIdleTimeMillis: 900000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      logAbandoned: false
      removeAbandoned: false
      removeAbandonedTimeout: 6000
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        allow: null
        url-pattern: /druid/*
        login-username: null
        login-password: null